# Generated by Django 5.1.1 on 2025-05-05 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cuisine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("country", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("slug", models.SlugField(blank=True, max_length=60, unique=True)),
                ("description", models.TextField()),
                (
                    "cooking_time",
                    models.PositiveIntegerField(
                        help_text="Total cooking time in minutes"
                    ),
                ),
                ("servings", models.IntegerField()),
                (
                    "difficulty",
                    models.CharField(
                        choices=[("E", "Easy"), ("M", "Medium"), ("H", "Hard")],
                        default="E",
                        max_length=1,
                    ),
                ),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("BF", "Breakfast"),
                            ("BR", "Brunch"),
                            ("LUN", "Lunch"),
                            ("DIN", "Dinner"),
                            ("DES", "Dessert"),
                            ("BEV", "Beverages"),
                            ("OTH", "Other"),
                        ],
                        default="OTH",
                        max_length=10,
                    ),
                ),
                ("ingredients", models.TextField()),
                ("instructions", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chef",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_apis",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cuisine_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.cuisine",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="api_recipe_created_e12d36_idx"
                    )
                ],
            },
        ),
    ]
