# Generated by Django 5.1.1 on 2025-05-05 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="category",
            field=models.CharField(
                choices=[
                    ("VEG", "Vegetarian"),
                    ("GLUT", "GlutenFree"),
                    ("LC", "LowCarb"),
                    ("PAL", "Paleo"),
                ],
                default="VEG",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="recipe_image",
            field=models.ImageField(default="default.jpg", upload_to="recipe_images"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="instructions",
            field=models.CharField(max_length=1000),
        ),
    ]
