# Generated by Django 5.1.1 on 2025-05-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_recipe_category_recipe_recipe_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="category",
            field=models.CharField(
                choices=[
                    ("Vegetarian", "Vegetarian"),
                    ("Gluten Free", "GlutenFree"),
                    ("Low Carb", "LowCarb"),
                    ("Paleo", "Paleo"),
                ],
                default="Vegetarian",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="difficulty",
            field=models.CharField(
                choices=[("Easy", "Easy"), ("Medium", "Medium"), ("Hard", "Hard")],
                default="Easy",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="meal_type",
            field=models.CharField(
                choices=[
                    ("Breakfast", "Breakfast"),
                    ("Brunch", "Brunch"),
                    ("Lunch", "Lunch"),
                    ("Dinner", "Dinner"),
                    ("Dessert", "Dessert"),
                    ("Beverages", "Beverages"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=10,
            ),
        ),
    ]
