# Generated by Django 5.1.1 on 2025-05-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_recipe_id_alter_recipe_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="recipe_image",
            field=models.ImageField(default="default.jpg", upload_to="recipe_images/"),
        ),
    ]
