# Generated by Django 5.1.1 on 2024-11-07 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='todo_task_created_8a6456_idx',
            old_name='todo_tasks_created_489ee2_idx',
        ),
    ]
